### ISSUE TITLE
Old sources?

### ISSUE THREAD

**Issue by rivimey** [pmachapman/memacs#4]
I saw your comment about finding sources for UE and agree that it's looking harder to find, and it would be a great shame. if it disappeared.

I was looking at some old source trees and found a copy of UE 3.12 (probably from the Amiga port); would you have any interest in adding a v3 branch to your repo?

**Comment by pmachapman** [comment]
Yes, I think that's a good idea - please attach the zip file, and I will create the branch.

We have a copy of 3.12 in the tree - I will fork from that, if it is similar: https://github.com/pmachapman/memacs/commit/ed1d9c84bfd1c483d3fe6626735ad9656d2761cf

**Comment by rivimey** [comment]
Here's the version i have.

I note it includes a compiled AmigaDOS executable but not intermediate objects, and a 'grep' shows:

ue312/src/edebug.c:   Significant changes for GCC (c) 1996 Ruth Ivimey-Cook
ue312/src/amigados.c:   Significant changes for GCC (c) 1996 Ruth Ivimey-Cook
ue312/src/old-ados.c:                   Significant changes for GCC (c) 1996 Ruth Ivimey-Cook
ue312/h/edebug.h:   Significant changes for GCC (c) 1996 Ruth Ivimey-Cook

I don't really remember what the changes were about or whether they were complete, sorry. I expect I was trying to compile the existing amiga port under GCC rather than Metacomco cc (the standard Amiga compiler of the day, but expensive).

I hereby release any copyright I had in the attached files.
 
[ue312-amiga.tar.gz](https://github.com/pmachapman/memacs/files/5548419/ue312-amiga.tar.gz)

PS. Have you seen: http://www.edm2.com/index.php/MicroEMACS

**Comment by pmachapman** [comment]
Thank you for that, I will create a branch.

No I haven't seen that page - thanks for sending it through.

The page is right in pointing out the copyright mess. I've only really put this repo online because of Daniel's death, and the fact that I wanted to share my getting it running on 64-bit Windows. If his estate wish to assert copyright, and take over what is here (for v4+), that is no problem. I am actually amazed that his server is still running - I have no idea who is keeping it going.

**Comment by pmachapman** [comment]
I've pushed a branch to https://github.com/pmachapman/memacs/tree/ue312. I haven't programmed an Amiga in about 25 years (I still have 2 in a box somewhere), so maybe when I get them up and running, I will try the code out - I only have Workbench 3.1 I think, which the code looks like it will run on.
